FROM python:3

# Setting up working directory
WORKDIR /app

# Copying the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the app.py when the container launches
CMD ["python","app.py"]

